[package]
name = "md-to-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "md_to_html"
path = "src/lib.rs"

[[bin]]
name = "mdtohtml"
path = "src/bin.rs"

[dependencies]
